### ISSUE TITLE
Creates tables/lists with classnames, but no meaningful layout or working links

### ISSUE THREAD

**Issue by peletiah** [Cobertos/DoxygenMediawikiBot#2]
After some fiddling I managed to get your bot to read and write doxygen-data, but the wiki-pages it creates only seem to be lists of classes and their methods, with broken wiki-syntax:
[https://imgur.com/a/xXLGkJB](Screenshot of a typical page)

The docs that are exported to the tmp-directory by doxygen are looking good, they have working layout, links to classes and methods with parameters and the description. I was expecting a similar structure to be created in the wiki. But all the bot does is create tables with text as in the image above.

Before diving into the code myself - am I missing something or is that all it can do right now?

**Comment by Cobertos** [comment]
Hmm, it's been a long time since I wrote/used this so I'm only as useful as digging through the code myself as well. IIRC, it will create pages for every class and method (like normally comes out of Doxygen) and also adds MediaWiki categories to recreate the "list" type pages in Doxygen instead of trying to duplicate them as separate pages. It was supposed to handle the inheritance images (uploading and relinking them), <a> tags, and some other stuff.

The basic process is as follows though (with links to source):
[At the highest level](https://github.com/Cobertos/DoxygenMediawikiBot/blob/master/doxymw.py#L205-L225) is basically generates the Doxygen docs as normal HTML, throws the [doxygen HTML files of our choice](https://github.com/Cobertos/DoxygenMediawikiBot/blob/master/doxymw.py#L130-L151) into a [`DoxygenHTMLPage()`](https://github.com/Cobertos/DoxygenMediawikiBot/blob/master/doxymwpage.py#L337) which handles parsing and conversion, and then uploads it all the wiki.

**Comment by peletiah** [comment]
Ok, thanks, I'll try to continue from there.

**Comment by peletiah** [comment]
I've now realized that it was simply the `doxygen_filePrefixes` in doxymw.py which didn't match my filenames. Now I get much more nicely formatted class-documentation, thanks!
